# Generated by Django 4.2.7 on 2023-11-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continue_register',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='continue_register',
            name='password',
        ),
        migrations.AddField(
            model_name='continue_register',
            name='account_type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='continue_register',
            name='branch',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='continue_register',
            name='district',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='continue_register',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='continue_register',
            name='materials_provide',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
