# Generated by Django 4.2.7 on 2023-11-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_district_branch_alter_continue_register_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continue_register',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='continue_register',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='continue_register',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
