# Generated by Django 4.2.7 on 2023-11-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_continue_register_age_continue_register_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continue_register',
            name='account_type',
            field=models.CharField(choices=[('current_account', 'Current account'), ('savings', 'Savings account'), ('fd', 'Fixed deposit accoutnt'), ('nri', 'NRI accounts')], default=None, max_length=100),
        ),
    ]
